// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWl_E9bElYpry7-Mgsf6KSq2jkY2ZiZ94',
    appId: '1:153252829241:web:b8d3c5b489bc803c9895e8',
    messagingSenderId: '153252829241',
    projectId: 'pitsias-35679',
    authDomain: 'pitsias-35679.firebaseapp.com',
    storageBucket: 'pitsias-35679.appspot.com',
    measurementId: 'G-6RBCHZQ9WN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1zw7q5ow6DgWGpBEyuU1heZWEvZLC4Lw',
    appId: '1:153252829241:android:a84da1d6efd67dc59895e8',
    messagingSenderId: '153252829241',
    projectId: 'pitsias-35679',
    storageBucket: 'pitsias-35679.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMThQN2WanDTWO0dZnQQxAyEs1fDd_gus',
    appId: '1:153252829241:ios:0db46577f9e336529895e8',
    messagingSenderId: '153252829241',
    projectId: 'pitsias-35679',
    storageBucket: 'pitsias-35679.appspot.com',
    iosBundleId: 'cz.rtsolutions.pitsiasAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMThQN2WanDTWO0dZnQQxAyEs1fDd_gus',
    appId: '1:153252829241:ios:24b627c5e9ed0f5e9895e8',
    messagingSenderId: '153252829241',
    projectId: 'pitsias-35679',
    storageBucket: 'pitsias-35679.appspot.com',
    iosBundleId: 'cz.rtsolutions.pitsiasAdmin.RunnerTests',
  );
}
